CREATE TABLE `rbac`.`T_SFC_STAFFEXTENDINFO`  (
  `STAFFID` varchar(20) NOT NULL,
  `SEX` varchar(8),
  `ISMARRIED` varchar(2),
  `POLITICALSTANDING` varchar(20),
  `JOINPARTYDATE` datetime,
  `IDCARDCODE` varchar(20),
  `TELNO` varchar(20),
  `EDUCATION` varchar(10),
  `GRADUATEDATE` datetime,
  `UNIVERSITY` varchar(60),
  `MAJOR` varchar(60),
  `JOINDATE` datetime,
  `JOINLEN` double(4, 1),
  `COMPANYID` varchar(20),
  `DISMISSIONDATE` datetime,
  `DOMICILEDPLACE` varchar(100),
  `EMERGLINKMAN1` varchar(20),
  `EMERGENCETELNO1` varchar(20),
  `EMERGLINKMAN2` varchar(20),
  `EMERGENCETELNO2` varchar(20),
  `FAXNO` varchar(20),
  `HOMEADDRESS` varchar(100),
  `POSTCODE` varchar(10),
  `DWELLING` varchar(100),
  `CERTDESC` varchar(2000),
  `PHOTO` varchar(100),
  `BIRTHDAY` datetime,
  `AGE` int(3),
  `NATION` varchar(10),
  `EMPLOYMENTEXPERIENCE` varchar(1000),
  `NATIVEPLACE` varchar(100),
  `EDUCATIONEXPERIENCE` varchar(1000),
  `FOREIGNLANGUAGE` varchar(200),
  `FOREIGNLANGUAGELEVEL` varchar(200),
  `COMPUTERLEVEL` varchar(200),
  `LENGTHOFSERVICE` int(3),
  `MOBILEPHONE` varchar(50),
  `EMAILADDRESS` varchar(50),
  `CERTANDDESC` varchar(2000),
  `COSHORTTELNUM` varchar(50),
  `BATCHNUM` varchar(60),
  PRIMARY KEY (`STAFFID`)
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;